---
# tasks file for mongodb

# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

# Configure Transparent Huge Pages.
- include: hugepages.yml
  when: mongodb_disable_thp

# Configure MongoDB.
- include: configure.yml
